import React from 'react';
import { BookOpen, HelpCircle, ShieldCheck, Zap, Wifi, AlertTriangle, Keyboard } from 'lucide-react';
import { Card } from '../components/Common';

const ManualPage = () => (
  <div className="grid">
     <div className="col-12">
        <h2 style={{ fontSize: '22px', marginBottom: '8px' }}>User Manual</h2>
        <p className="text-muted" style={{ marginBottom: '32px' }}>Comprehensive guide for RemoteLink Pro Utility.</p>
     </div>

     <div className="col-8">
        <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
           <section>
              <h3 style={{ fontSize: '18px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}><Wifi size={18} /> Getting Started</h3>
              <p className="text-secondary" style={{ lineHeight: 1.6 }}>
                 RemoteLink connects your phone and PC over your trusted Wi-Fi or hotspot after you approve pairing.
                 To begin, start the Remote Engine in the header and connect from your Android device. Internet is not required for local mode.
              </p>
           </section>

           <section>
              <h3 style={{ fontSize: '18px', marginBottom: '16px' }}>Connection Workflow</h3>
              <div className="grid">
                 <div className="col-6">
                    <h4 style={{ fontSize: '14px', marginBottom: '8px' }}>1. Locate PC IP</h4>
                    <p className="text-muted" style={{ fontSize: '13px' }}>Start Remote Engine, then copy the Recommended Host IP. Use an IP from the same Wi-Fi/Ethernet network as your phone. Do not use VirtualBox, VMware, WSL, Docker, vEthernet, or Bluetooth IPs for real phone pairing.</p>
                 </div>
                 <div className="col-6">
                    <h4 style={{ fontSize: '14px', marginBottom: '8px' }}>2. Pairing Code</h4>
                    <p className="text-muted" style={{ fontSize: '13px' }}>A 6-digit random code is generated by the desktop engine. Enter this on mobile to initiate the handshake, then approve the request on desktop.</p>
                 </div>
              </div>
           </section>

           <section>
              <h3 style={{ fontSize: '18px', marginBottom: '16px' }}>Real Phone Pairing</h3>
              <p className="text-secondary" style={{ lineHeight: 1.6 }}>
                 Step 1: Start Remote Engine. Step 2: Make sure phone and PC are on the same Wi-Fi.
                 Step 3: On mobile, enter the Recommended Host IP and Pairing Code. Step 4: Approve the request on PC.
                 Step 5: If the phone cannot reach this PC, open Pairing & Devices and use Fix Local Firewall Access.
                 If scan finds nothing, enter the Recommended Host IP manually; some hotspots block discovery scan.
              </p>
              <p className="text-secondary" style={{ lineHeight: 1.6, marginTop: '12px' }}>
                 Do not use RemoteLink on untrusted public Wi-Fi unless you understand the local network risk.
                 If Windows asks for local network permission, allow RemoteLink only on trusted private networks or your own hotspot.
              </p>
           </section>

           <section>
              <h3 style={{ fontSize: '18px', marginBottom: '16px' }}>Interactive Controls</h3>
              <p className="text-secondary" style={{ lineHeight: 1.6, marginBottom: '16px' }}>
                 Once connected, your phone can send real mouse and keyboard input to the paired Windows PC.
                 Only approve devices you trust. Disconnecting the session stops input and preview streaming.
              </p>
              <div style={{ padding: '20px', background: 'var(--bg-card)', borderRadius: '12px', border: '1px solid var(--border-subtle)' }}>
                 <h4 style={{ fontSize: '14px', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}><Zap size={14} color="var(--accent-amber)" /> Sticky Modifiers</h4>
                 <p className="text-muted" style={{ fontSize: '13px', margin: 0 }}>
                    Long-press Ctrl, Alt, or Shift on mobile to keep them "held" on the PC. 
                    This allows for shortcuts like Ctrl+V without needing multiple fingers on the phone. 
                    Use "Release All Keys" if a modifier stays active.
                 </p>
              </div>
           </section>

           <section>
              <h3 style={{ fontSize: '18px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}><ShieldCheck size={18} color="var(--accent-green)" /> Privacy & Security</h3>
              <p className="text-secondary" style={{ lineHeight: 1.6 }}>
                 Every new mobile session requires the desktop engine, matching pairing code, and host approval.
                 Connection status is shown in the app. Mobile screen sharing requires explicit Android screen-capture consent.
              </p>
           </section>
        </div>
     </div>

     <div className="col-4">
        <Card title="Troubleshooting" icon={HelpCircle}>
           <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
              <div>
                 <h4 style={{ fontSize: '13px', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '8px' }}><AlertTriangle size={14} color="var(--accent-amber)" /> Device not found</h4>
                 <p className="text-muted" style={{ fontSize: '12px' }}>Ensure both devices are on the same Wi-Fi or hotspot. Use the Recommended Host IP if scan finds nothing.</p>
              </div>
              <div>
                 <h4 style={{ fontSize: '13px', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '8px' }}><ShieldCheck size={14} color="var(--accent-amber)" /> Firewall</h4>
                 <p className="text-muted" style={{ fontSize: '12px' }}>Use Pairing & Devices &gt; Fix Local Firewall Access. It requests Windows permission for RemoteLink local network access.</p>
              </div>
              <div>
                 <h4 style={{ fontSize: '13px', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '8px' }}><Zap size={14} color="var(--accent-amber)" /> High Latency</h4>
                 <p className="text-muted" style={{ fontSize: '12px' }}>Switch to a 5GHz Wi-Fi band or connect the PC via Ethernet to reduce jitter.</p>
              </div>
              <div>
                 <h4 style={{ fontSize: '13px', marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '8px' }}><Keyboard size={14} color="var(--accent-amber)" /> Stuck Modifiers</h4>
                 <p className="text-muted" style={{ fontSize: '12px' }}>If keys remain "held", go to Settings &gt; Safety and click "Release All", or use Release All Keys on Overview.</p>
              </div>
           </div>
        </Card>

        <div style={{ marginTop: '24px', padding: '24px', background: 'rgba(59, 130, 246, 0.05)', borderRadius: '16px', border: '1px solid rgba(59, 130, 246, 0.1)' }}>
           <h4 style={{ fontSize: '14px', marginBottom: '8px', color: 'var(--accent-blue)', display: 'flex', alignItems: 'center', gap: '8px' }}><Wifi size={16} /> Local Network Only</h4>
           <p className="text-muted" style={{ fontSize: '12px', margin: 0 }}>
              RemoteLink 1.0 is designed for trusted Wi-Fi or a personal hotspot. It does not use a cloud relay.
           </p>
        </div>
     </div>
  </div>
);

export default ManualPage;
