import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class ManualScreen extends StatelessWidget {
  const ManualScreen({super.key});

  static const List<Widget> _sections = [
    _ManualSection(
      title: 'Getting Started',
      content:
          'RemoteLink connects your phone and PC over your trusted Wi‑Fi or hotspot after you approve pairing. Start the desktop Remote Engine to begin.',
    ),
    _ManualSection(
      title: 'Connect to PC',
      content:
          'Ensure your phone and PC are on the same Wi‑Fi or your own phone hotspot. Internet is not required for local mode. '
          'Enter the Recommended Host IP and Pairing Code into the Connect screen, then approve the request on the PC. If scan finds nothing, connect manually; some hotspots block local discovery.',
    ),
    _ManualSection(
      title: 'Find PC IP',
      content:
          'Open the RemoteLink desktop app — it will show your actual Host IP in the top header. (Example only: 192.168.0.24)',
    ),
    _ManualSection(
      title: 'Pairing Code',
      content:
          'A random 6-digit code is generated by the PC engine. The code must match before the desktop can approve the request.',
    ),
    _ManualSection(
      title: 'Troubleshooting',
      content: '• Wrong IP: Re-verify the address in the desktop app header.\n'
          '• Code Expired: Restart the RemoteLink engine on your PC.\n'
          '• Network Mismatch: Ensure devices are on the same Wi‑Fi SSID.\n'
          '• Engine Stopped: Ensure the "START ENGINE" button on PC is clicked.\n'
          '• Firewall: Use the desktop Pairing & Devices screen to fix local firewall access. Possible firewall or network isolation issues can stop the phone from reaching the PC.\n'
          '• Wrong adapter: Do not use VirtualBox, VMware, WSL, Docker, vEthernet, or Bluetooth IPs for real phone pairing.\n'
          '• Multiple IPs: Try another detected LAN IP shown in the desktop app.\n'
          '• Shortcuts stuck: Tap "Release All Keys" on the Remote screen to clear held modifiers.\n'
          '• Touchpad too sensitive: Lower the Mouse Speed slider in mobile settings.',
    ),
    _ManualSection(
      title: 'Mouse Control',
      content:
          'After desktop approval, touchpad and click actions can move the real mouse on the paired PC. Only approve computers and sessions you trust.',
    ),
    _ManualSection(
      title: 'Typing to PC',
      content:
          'Use the text field on the Remote screen to type on the paired PC. Disconnect the session to stop remote input.',
    ),
    _ManualSection(
      title: 'Shortcut Keys',
      content:
          'Shortcuts are grouped into Basic Keys, Modifiers, Actions, and Function Keys panels on the Remote screen. Tap a panel header to expand or collapse it.',
    ),
    _ManualSection(
      title: 'Hold Modifiers',
      content:
          'Tap CTRL, ALT, SHIFT, or WIN in the Modifiers panel to toggle them as "held". This allows you to perform complex shortcuts like CTRL+C.',
    ),
    _ManualSection(
      title: 'Security Rules',
      content:
          'Every connection requires the desktop engine, matching pairing code, and approval on the PC. Use RemoteLink only on trusted/private networks or your own hotspot. Do not use untrusted public Wi‑Fi unless you understand the risk. Phone screen sharing requires Android screen-capture consent. Use Release All Keys if modifiers become stuck.',
    ),
    _ManualSection(
      title: 'Support',
      content:
          'For support, use the official store listing or support page when available.\n'
          'Privacy Policy: To be added before store release\n'
          'Support Page: To be added before store release',
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Application Manual',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
      ),
      body: SafeArea(
        child: LayoutBuilder(
          builder: (context, constraints) {
            if (constraints.maxWidth >= 720) {
              // Landscape / wide: split sections across two readable columns.
              final left = <Widget>[];
              final right = <Widget>[];
              for (var i = 0; i < _sections.length; i++) {
                (i.isEven ? left : right).add(_sections[i]);
              }
              return SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(child: Column(children: left)),
                    const SizedBox(width: 48),
                    Expanded(child: Column(children: right)),
                  ],
                ),
              );
            }
            return ListView(
              padding: const EdgeInsets.all(24),
              children: _sections,
            );
          },
        ),
      ),
    );
  }
}

class _ManualSection extends StatelessWidget {
  final String title;
  final String content;
  const _ManualSection({required this.title, required this.content});

  @override
  Widget build(BuildContext context) {
    final c = context.colors;
    return Padding(
      padding: const EdgeInsets.only(bottom: 32.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title,
              style: TextStyle(
                  fontSize: 18, fontWeight: FontWeight.w600, color: c.blue)),
          const SizedBox(height: 12),
          Text(content,
              style:
                  TextStyle(fontSize: 14, color: c.textSecondary, height: 1.6)),
          const SizedBox(height: 16),
          Divider(color: c.border),
        ],
      ),
    );
  }
}
