import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class ManualScreen extends StatelessWidget {
  const ManualScreen({super.key});

  static const List<Widget> _sections = [
          _ManualSection(
            title: 'Getting Started',
            content: 'Remote Link pairs your Android device with your PC over your local network. Start the desktop Remote Engine to begin.',
          ),
          _ManualSection(
            title: 'Connect to PC',
            content: 'Ensure your phone and PC are on the same Wi‑Fi SSID. Enter the Host IP and Pairing Code into the Connect screen. '
                'Use the Recommended Host IP from the desktop app. The mobile app connects to ws://HOST_IP:47777 and waits for approval on the desktop. Scanning remains separate and never invents a desktop.',
          ),
          _ManualSection(
            title: 'Find PC IP',
            content: 'Open the Remote Link desktop app — it will show your actual Host IP in the top header. (Example only: 192.168.0.24)',
          ),
          _ManualSection(
            title: 'Pairing Code',
            content: 'A random 6-digit code is generated by the PC engine. The code must match before the desktop can approve the request.',
          ),
          _ManualSection(
            title: 'Troubleshooting',
            content: '• Wrong IP: Re-verify the address in the desktop app header.\n'
                     '• Code Expired: Restart the RemoteLink engine on your PC.\n'
                     '• Network Mismatch: Ensure devices are on the same Wi‑Fi SSID.\n'
                     '• Engine Stopped: Ensure the "START ENGINE" button on PC is clicked.\n'
                     '• Firewall: Allow RemoteLink on private/local networks if Windows Firewall prompts.\n'
                     '• Wrong adapter: Do not use VirtualBox, VMware, WSL, Docker, vEthernet, or Bluetooth IPs for real phone pairing.\n'
                     '• Multiple IPs: Try another detected LAN IP shown in the desktop app.\n'
                     '• Shortcuts stuck: Tap "Release All Keys" on the Remote screen to clear held modifiers.\n'
                     '• Touchpad too sensitive: Lower the Mouse Speed slider in mobile settings.',
          ),
          _ManualSection(
            title: 'Mouse Control',
            content: 'Phase 1 sends command_log messages only. Touchpad and click actions are shown in the desktop activity log and do not move the real PC cursor.',
          ),
          _ManualSection(
            title: 'Typing to PC',
            content: 'Use the text field at the bottom of the Remote screen to send a command_log text entry to the desktop. It does not inject keystrokes in Phase 1.',
          ),
          _ManualSection(
            title: 'Shortcut Keys',
            content: 'Shortcuts are grouped into Basic Keys, Modifiers, Actions, and Function Keys panels on the Remote screen. Tap a panel header to expand or collapse it.',
          ),
          _ManualSection(
            title: 'Hold Modifiers',
            content: 'Tap CTRL, ALT, SHIFT, or WIN in the Modifiers panel to toggle them as "held". This allows you to perform complex shortcuts like CTRL+C.',
          ),
          _ManualSection(
            title: 'Security Rules',
            content: 'Remote Link never allows hidden access. Every connection requires physical approval on the host PC screen. This version logs commands only; real control and streaming are later phases.',
          ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Application Manual', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
      ),
      body: SafeArea(
        child: LayoutBuilder(
          builder: (context, constraints) {
            if (constraints.maxWidth >= 720) {
              // Landscape / wide: split sections across two readable columns.
              final left = <Widget>[];
              final right = <Widget>[];
              for (var i = 0; i < _sections.length; i++) {
                (i.isEven ? left : right).add(_sections[i]);
              }
              return SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(child: Column(children: left)),
                    const SizedBox(width: 48),
                    Expanded(child: Column(children: right)),
                  ],
                ),
              );
            }
            return ListView(
              padding: const EdgeInsets.all(24),
              children: _sections,
            );
          },
        ),
      ),
    );
  }
}

class _ManualSection extends StatelessWidget {
  final String title;
  final String content;
  const _ManualSection({required this.title, required this.content});

  @override
  Widget build(BuildContext context) {
    final c = context.colors;
    return Padding(
      padding: const EdgeInsets.only(bottom: 32.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: c.blue)),
          const SizedBox(height: 12),
          Text(content, style: TextStyle(fontSize: 14, color: c.textSecondary, height: 1.6)),
          const SizedBox(height: 16),
          Divider(color: c.border),
        ],
      ),
    );
  }
}
