import 'package:flutter/material.dart';
import '../theme/app_theme.dart';

class ManualScreen extends StatelessWidget {
  const ManualScreen({super.key});

  static const List<Widget> _sections = [
          _ManualSection(
            title: 'Getting Started',
            content: 'RemoteLink Pro allows you to control your PC from your Android device over a local network. Start the engine on your PC to begin.',
          ),
          _ManualSection(
            title: 'Connect to PC',
            content: 'Ensure your phone and PC are on the same Wi‑Fi SSID. Enter the Host IP and Pairing Code into the Connect screen. '
                'Scanning will detect desktops only after local discovery/pairing is implemented — for now, enter the Host IP from the desktop app manually.',
          ),
          _ManualSection(
            title: 'Find PC IP',
            content: 'Open the RemoteLink Pro desktop app — it will show your actual Host IP in the top header. (Example only: 192.168.0.24)',
          ),
          _ManualSection(
            title: 'Pairing Code',
            content: 'A random 6-digit code is generated by the PC for security. It expires every 60 minutes or on engine restart.',
          ),
          _ManualSection(
            title: 'Troubleshooting',
            content: '• Wrong IP: Re-verify the address in the desktop app header.\n'
                     '• Code Expired: Restart the RemoteLink engine on your PC.\n'
                     '• Network Mismatch: Ensure devices are on the same Wi‑Fi SSID.\n'
                     '• Engine Stopped: Ensure the "START ENGINE" button on PC is clicked.\n'
                     '• Firewall: Ensure RemoteLink is allowed through Windows Firewall.\n'
                     '• Shortcuts stuck: Tap "Release All Keys" on the Remote screen to clear held modifiers.\n'
                     '• Touchpad too sensitive: Lower the Mouse Speed slider in mobile settings.',
          ),
          _ManualSection(
            title: 'Mouse Control',
            content: 'Use the touchpad area to move the PC cursor. Single tap for Left Click, two-finger tap for Right Click. Double-tap and drag for selection.',
          ),
          _ManualSection(
            title: 'Typing to PC',
            content: 'Use the text field at the bottom of the Remote screen to send keystrokes to your PC. Tap the Send icon to inject the text.',
          ),
          _ManualSection(
            title: 'Shortcut Keys',
            content: 'Shortcuts are grouped into Basic Keys, Modifiers, Actions, and Function Keys panels on the Remote screen. Tap a panel header to expand or collapse it.',
          ),
          _ManualSection(
            title: 'Hold Modifiers',
            content: 'Tap CTRL, ALT, SHIFT, or WIN in the Modifiers panel to toggle them as "held". This allows you to perform complex shortcuts like CTRL+C.',
          ),
          _ManualSection(
            title: 'Security Rules',
            content: 'RemoteLink Pro never allows hidden access. Every connection requires physical approval on the host PC screen.',
          ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Application Manual', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600)),
      ),
      body: SafeArea(
        child: LayoutBuilder(
          builder: (context, constraints) {
            if (constraints.maxWidth >= 720) {
              // Landscape / wide: split sections across two readable columns.
              final left = <Widget>[];
              final right = <Widget>[];
              for (var i = 0; i < _sections.length; i++) {
                (i.isEven ? left : right).add(_sections[i]);
              }
              return SingleChildScrollView(
                padding: const EdgeInsets.all(24),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(child: Column(children: left)),
                    const SizedBox(width: 48),
                    Expanded(child: Column(children: right)),
                  ],
                ),
              );
            }
            return ListView(
              padding: const EdgeInsets.all(24),
              children: _sections,
            );
          },
        ),
      ),
    );
  }
}

class _ManualSection extends StatelessWidget {
  final String title;
  final String content;
  const _ManualSection({required this.title, required this.content});

  @override
  Widget build(BuildContext context) {
    final c = context.colors;
    return Padding(
      padding: const EdgeInsets.only(bottom: 32.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: c.blue)),
          const SizedBox(height: 12),
          Text(content, style: TextStyle(fontSize: 14, color: c.textSecondary, height: 1.6)),
          const SizedBox(height: 16),
          Divider(color: c.border),
        ],
      ),
    );
  }
}
